sudo: false

language: python

python:
  - 3.5.0b3
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - pypy

matrix:
  allow_failures:
    - python: 3.5.0b3

services:
  - redis-server

install:
  - make install

script:
  - make coverage

after_success:
  - coveralls
