sudo: false

language: python

python:
  - nightly
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - pypy

matrix:
  allow_failures:
    - python: nightly

services:
  - redis-server

install:
  - make install

script:
  - make coverage

after_success:
  - coveralls
